import { test, expect } from '@playwright/test'
const cv = 'ANA EXEMPLO\nana@example.com\n\nEXPERIÊNCIA\nDesenvolvedora na Empresa Exemplo — 2022–2025\n\nHABILIDADES\nPython, React, C# e .NET\n\nFORMAÇÃO\nEngenharia de Software'
test('configurar, criar vaga, gerar e versionar PDF, registrar e remover candidatura', async ({page,request}, info) => {
 const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
 await page.route('**/api/settings', async route => { if (route.request().method() !== 'GET') return route.continue(); const response = await route.fetch(); await route.fulfill({response,json:{...(await response.json()),autoApplyEnabled:'true',browserHeadless:'true'}}) })
 await page.goto('/settings')
 await page.getByLabel('Texto revisado do currículo').fill(cv)
 await page.getByLabel('Provedor',{exact:true}).selectOption('none')
 await page.getByLabel('Fontes habilitadas (JSON)').fill('["api"]')
 await page.getByRole('button',{name:'Salvar configurações'}).click()
 await expect(page.getByText('Configurações salvas',{exact:true})).toBeVisible()
 await page.reload()
 await expect(page.getByLabel('Texto revisado do currículo')).toHaveValue(cv)
 await page.getByRole('link',{name:'Dashboard'}).click()
 await page.getByRole('button',{name:'Nova Vaga',exact:true}).click()
 const add = page.getByRole('dialog')
 const title = 'Desenvolvedora Python ' + info.project.name
 await add.getByLabel('Título',{exact:true}).fill(title)
 await add.getByLabel('Empresa',{exact:true}).fill('Empresa fictícia')
 await add.getByLabel('URL',{exact:true}).fill('https://example.com/'+info.project.name)
 await add.getByLabel('Localização',{exact:true}).fill('Remoto Brasil')
 await add.getByLabel('Descrição',{exact:true}).fill('Desenvolvimento Python React C# remoto Brasil')
 await add.getByRole('button',{name:'Adicionar Vaga'}).click()
 await expect(add).not.toBeVisible()
 const card = page.getByRole('button').filter({has:page.getByRole('heading',{name:title,exact:true})})
 await card.focus(); await page.keyboard.press('Enter')
 const detail = page.getByRole('dialog')
 await detail.getByLabel('Etapa da candidatura').selectOption('adjusting_cv')
 await expect(detail.getByRole('link',{name:'Baixar PDF salvo'})).toBeVisible()
 await expect(detail.getByLabel('Texto do currículo')).toHaveValue(cv)
 const firstUrl = await detail.getByRole('link',{name:'Baixar PDF salvo'}).getAttribute('href')
 const pdf = await request.get(firstUrl!)
 expect(pdf.ok()).toBeTruthy(); expect((await pdf.body()).subarray(0,4).toString()).toBe('%PDF')
 await detail.getByLabel('Texto do currículo').fill(cv+'\nIDIOMAS\nPortuguês')
 await detail.getByRole('button',{name:'Salvar como nova versão'}).click()
 await expect(detail.getByLabel('Versão do currículo').locator('option')).toHaveCount(2)
 await expect(detail.getByLabel('Texto do currículo')).toHaveValue(cv+'\nIDIOMAS\nPortuguês')
 const firstId = firstUrl!.split('/').at(-2)!
 await detail.getByLabel('Versão do currículo').selectOption(firstId)
 await expect(detail.getByLabel('Texto do currículo')).toHaveValue(cv)
 await detail.getByLabel('Etapa da candidatura').selectOption('applied')
 await expect(detail.getByText(/Candidatura registrada em/)).toBeVisible()
 await page.screenshot({path:info.outputPath('curriculo.png'),fullPage:true})
 await detail.getByRole('button',{name:'Fechar',exact:true}).click()
 await page.reload(); await expect(card).toBeVisible()
 if(info.project.name==='mobile') expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
 await page.screenshot({path:info.outputPath('kanban.png'),fullPage:true})
 await card.click(); page.once('dialog',d=>d.accept())
 await page.getByRole('button',{name:'Remover vaga',exact:true}).click()
 await expect(page.getByRole('dialog')).not.toBeVisible()
 await expect(card).not.toBeVisible()
 expect(errors).toEqual([])
})
test('falhas de configuração, coleta e backend são visíveis', async ({page}) => {
 await page.goto('/settings')
 await page.getByLabel('Termos de busca (JSON)').fill('{}')
 await page.getByRole('button',{name:'Salvar configurações'}).click()
 await expect(page.getByText(/expected|array|lista|invalid/i).first()).toBeVisible()
 await page.getByLabel('Termos de busca (JSON)').fill('["Python"]')
 await page.getByLabel('Fontes habilitadas (JSON)').fill('["api"]')
 await page.getByLabel('APIs públicas JSON (JSON)').fill('[]')
 await page.getByRole('button',{name:'Salvar configurações'}).click()
 await expect(page.getByText('Configurações salvas',{exact:true})).toBeVisible()
 await page.getByRole('link',{name:'Dashboard'}).click()
 await page.getByRole('button',{name:'Buscar Vagas',exact:true}).click()
 await expect(page.getByText(/Última coleta: Falhou/)).toBeVisible()
 await page.getByText(/Última coleta: Falhou/).click()
 await expect(page.getByText(/Nenhuma URL configurada/)).toBeVisible()
 await page.route('**/api/jobs?*',route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":"Servidor indisponível"}'}))
 await page.getByLabel('Buscar vagas',{exact:true}).fill('offline')
 await expect(page.getByRole('alert')).toContainText('Servidor indisponível',{timeout:20000})
})
